### ISSUE TITLE
Discord invite link broken

### ISSUE THREAD

**Issue by jcbsnclr** [Jackojc/cane#10]
The discord invite link is broken. 

Also, as it so happens, after losing my phone, my Discord account (and any new ones I create) have been disabled! Is there any other way for me to contact you? Or the others in Turing Tarpit.

**Comment by Jackojc** [comment]
Hmm, the Discord invite appears to be valid, maybe you're being blocked from using it?

You can email me here: jackojc@gmail.com

Ill ask the others for means to contact them outside of Discord and forward them to the email listed on your profile.

**Comment by jcbsnclr** [comment]
that may be the case; I wasn't sure, since I tried using it without logging in, it seems I may have been IP banned from Discord lol

**Comment by Jackojc** [comment]
Might want to see if you can solicit a new IP address for your router to get around it.

**Comment by Jackojc** [comment]
Did you get those emails I sent you?
