### ISSUE TITLE
Simple fix for raspberry pi compilation error

### ISSUE THREAD

**Issue by shakfu** [Jackojc/cane#17]
FYI, I just tried compiling `cane` with both g++ (g++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110) and clang++ (Raspbian clang version 11.0.1-2+rpi1) on a raspbian  os.

It kept throwing an error regarding implicit conversion from the large ints in the `hash_bytes` function, and I had to cast to `size_t` as below. After this change, it compiled fine. 

```patch
$ git diff
diff --git a/src/util.hpp b/src/util.hpp
index dff526b..9eda4ab 100644
--- a/src/util.hpp
+++ b/src/util.hpp
@@ -47,8 +47,8 @@ namespace cane {
        }

        constexpr auto hash_bytes(const char* begin, const char* const end) {
-               size_t offset_basis = 14'695'981'039'346'656'037u;
-               size_t prime = 1'099'511'628'211u;
+               size_t offset_basis = (size_t)14'695'981'039'346'656'037u;
+               size_t prime = (size_t)1'099'511'628'211u;

                size_t hash = offset_basis;
```

**Comment by Jackojc** [comment]
Hey, thanks for letting me know about the issue! I wonder if we could use the `ul` suffix instead here?
```diff
-               size_t offset_basis = 14'695'981'039'346'656'037u;
-               size_t prime = 1'099'511'628'211u;
+               size_t offset_basis = 14'695'981'039'346'656'037ul;
+               size_t prime = 1'099'511'628'211ul;
```
Could you give it a try? If it doesn't help I can implement your fix.

**Comment by shakfu** [comment]
> can you give it a try

Sure. It didn't work:

```
$ make
cxx g++ | dbg no
mkdir -p build/
g++ -std=c++17 -Werror -Wall -Wextra -Wno-unused -pedantic -Wno-unused-parameter -DCANE_VERSION=\"2022-07-5\" -DNDEBUG  -march=native -O3  -Isrc/ -Imodules/conflict/include src/cane.cpp -o build/cane -flto -s -ljack
In file included from src/lib.hpp:20,
                 from src/cane.cpp:17:
src/util.hpp: In function ‘constexpr auto cane::hash_bytes(const char*, const char*)’:
src/util.hpp:50:25: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘14695981039346656037’ to ‘2216829733’ [-Werror=overflow]
   50 |   size_t offset_basis = 14'695'981'039'346'656'037ul;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/util.hpp:51:18: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1099511628211’ to ‘435’ [-Werror=overflow]
   51 |   size_t prime = 1'099'511'628'211ul;
      |                  ^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:16: cane] Error 1
```

**Comment by Jackojc** [comment]
Huh that's strange. Looks like size_t is smaller on your environment than mine (32 vs 64). I'm guessing raspbian is a 32-bit system? I think I can fix this by using a 32-bit version of the FNV-1a hash if `sizeof(size_t) == 4`. I will push a change that tomorrow that should hopefully fix it. The proposed solution will have the same issue as the above but without an error or warning so I don't think we can proceed with that.

**Comment by shakfu** [comment]
Well `uname -m` gives `aarch64'.  I'm using a raspbian bulleye-based audio-centric distribution ([patchbox os](https://blokas.io/patchbox-os)). It may be just configured in a particular way, it has a low-latency kernel ... on the other hand, I have been experiencing some weirdness... like not being able to install sonic-pi for raspberry pi.

... perhaps you shouldn't make the change after all if it's such a special case, and just document the issue if you prefer to retain the 64-bit version of the hash. 

Nonetheless, it you want to cater to 32-bit users then the change to a 32-bit hash makes sense too.

**Comment by Jackojc** [comment]
Hey I just pushed a fix, can you try it out? a98bb65e21d128ae6da7c27ed4854ff5d27ed8d6

**Comment by shakfu** [comment]
Yup it works fine 👍

**Comment by Jackojc** [comment]
Perfect, thanks for the report!
